DROP TABLE IF EXISTS `image_zoom_log`;
DROP TABLE IF EXISTS `album`;
DROP TABLE IF EXISTS `image`;
DROP TABLE IF EXISTS `fingerprint`;
DROP TABLE IF EXISTS `image_download_log`;
DROP TABLE IF EXISTS `image_session`;
DROP TABLE IF EXISTS `album_image`;
DROP TABLE IF EXISTS `comment`;
DROP TABLE IF EXISTS `user`;
